# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0004_auto_20190326_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('store', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns_to_be_paid', to='login_reg.User')),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns_paid', to='login_reg.User')),
            ],
        ),
    ]
