# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20190326_1629'),
        ('user_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='login_reg.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_home', to='login_reg.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joineddate',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_dates', to='user_dash.Home'),
        ),
        migrations.AddField(
            model_name='joineddate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_date', to='login_reg.User'),
        ),
    ]
