# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 19:20
from __future__ import unicode_literals

import apps.user_dash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0002_auto_20190326_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='join_id',
            field=models.CharField(default=apps.user_dash.models.create_join_id, max_length=6),
        ),
    ]
