# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0004_auto_20190326_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joineddate',
            name='home',
        ),
        migrations.RemoveField(
            model_name='joineddate',
            name='member',
        ),
        migrations.RemoveField(
            model_name='home',
            name='members',
        ),
        migrations.RemoveField(
            model_name='home',
            name='owner',
        ),
        migrations.DeleteModel(
            name='JoinedDate',
        ),
    ]
