# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20190325_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_home',
        ),
    ]
