# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20190326_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(default=''),
        ),
    ]
