# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0005_auto_20190326_1939'),
        ('login_reg', '0004_auto_20190326_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_dates', to='user_dash.Home')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user_dash.Home'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_dash.Home'),
        ),
        migrations.AddField(
            model_name='joineddate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_date', to='login_reg.User'),
        ),
    ]
