# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0005_auto_20190326_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='user_dash.Home'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='user_dash.Home'),
        ),
    ]
