# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0006_auto_20190327_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(default='/static/user_dash/img/default.png'),
        ),
    ]
